_BASE_: "Base-CenterMask-Lite-VoVNet.yaml"
MODEL:
  WEIGHTS: "https://www.dropbox.com/s/q98pypf96rhtd8y/vovnet39_ese_detectron2.pth?dl=1"
  VOVNET:
    CONV_BODY : "V-39-eSE"
  PIXEL_MEAN: (0, 0, 0)
  PIXEL_STD: (1, 1, 1)
  MASKIOU_ON: False
SOLVER:
  STEPS: (300000, 340000)
  MAX_ITER: 360000
OUTPUT_DIR: "output/centermask/CenterMask-Lite-V-39-ms-4x"
